name: auto_mappr_annotation
description: Annotations for the auto_mappr code-generator of mapping between objects with ease.
version: 2.3.0
repository: https://github.com/netglade/auto_mappr
issue_tracker: https://github.com/netglade/auto_mappr/issues

environment:
  sdk: ^3.6.0
resolution: workspace

dev_dependencies:
  netglade_analysis: ^16.1.0
  test: ^1.25.0
