name: auto_mappr_annotation_example
description: Example project
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  auto_mappr_annotation: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.14
  netglade_analysis: ^15.0.0
  test: ^1.25.14
