include: package:netglade_analysis/lints.yaml

analyzer:
  exclude:
    - test/integration/error_fixture/**

dart_code_metrics:
  extends:
    - package:netglade_analysis/dcm.yaml
  pubspec-rules:
    prefer-publish-to-none: false
    # TODO: Support analyzer same way as json_serializable https://github.com/google/json_serializable.dart/pull/1333
    prefer-caret-version-syntax: false
  rules:
    avoid-unnecessary-call: false # the Expression API uses a lot of `.call` which is clearer
    avoid-top-level-members-in-tests:
      exclude:
        - test/integration/fixture/**
    avoid-non-null-assertion: false # TODO
    avoid-nullable-interpolation: false # TODO
    prefer-boolean-prefixes: false # TODO
    avoid-passing-default-values: false # TODO
    avoid-commented-out-code: false # code examples in comments
    prefer-single-declaration-per-file: false # TODO
    prefer-named-parameters: false # TODO