name: auto_mappr
description: Code generation for mapping between different objects with ease.
version: 2.7.0
repository: https://github.com/netglade/auto_mappr
issue_tracker: https://github.com/netglade/auto_mappr/issues
screenshots:
  - description: The auto_mappr package logo.
    path: doc/icon.png

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  # TODO: Support analyzer same way as json_serializable https://github.com/google/json_serializable.dart/blob/master/json_serializable/pubspec.yaml
  analyzer: ">=6.5.0 <8.0.0"
  auto_mappr_annotation: ^2.3.0
  build: ^2.3.1
  built_collection: ^5.1.1
  code_builder: ^4.4.0
  collection: ^1.17.0
  equatable: ^2.0.7
  get_it: ^8.0.0
  meta: ^1.8.0
  path: ^1.8.2
  source_gen: ^1.2.6

dev_dependencies:
  build_runner: ^2.4.10
  generator_test: ^0.3.1
  mocktail: ^1.0.0
  netglade_analysis: ^15.0.0
  source_gen_test: ^1.0.4
  test: ^1.25.8
