name: examples_freezed
description: Example project with AutoMappr and Freezed integration
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  auto_mappr_annotation: ^2.3.0
  equatable: ^2.0.7
  freezed_annotation: ^2.2.0

dev_dependencies:
  auto_mappr: ^2.6.0
  build_runner: ^2.0.0
  freezed: ^2.5.8
  netglade_analysis: ^16.1.0
  test: '>=1.25.0 <2.0.0'

