name: examples_json_serializable
description: Example project with AutoMappr and JsonSerializable
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  auto_mappr_annotation: ^2.2.1
  json_annotation: ^4.8.1

dev_dependencies:
  auto_mappr: ^2.5.1
  build_runner: ^2.0.0
  json_serializable: ^6.6.1
  netglade_analysis: ^15.0.0
  test: ^1.25.8
