name: examples_injectable
description: Example project how to use AutoMappr with Injectable
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  auto_mappr_annotation: ^2.3.0
  equatable: ^2.0.5
  get_it: ^7.3.0
  injectable: ^2.5.0

dev_dependencies:
  auto_mappr: ^2.6.0
  build_runner: ^2.0.0
  injectable_generator: ^2.6.2
  netglade_analysis: ^15.0.0
  test: ^1.25.8
