name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  auto_mappr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - uses: bluefireteam/melos-action@v3

      - name: Generate AutoMappr files
        run: melos run gen:build-all

      - name: Analyze
        run: melos run lint:dart

      - name: Install DCM
        uses: CQLabs/setup-dcm@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run DCM
        uses: CQLabs/dcm-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ci-key: oss
          email: oss
          folders: .
          fatal-found: true

      - name: Test
        run: melos run test
