name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  auto_mappr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Configure FVM
        uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - uses: bluefireteam/melos-action@v3

      - name: Generate AutoMappr files
        run: melos run gen:build-all

      - name: Analyze
        run: melos run lint:dart

      - name: Install DCM
        uses: CQLabs/setup-dcm@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run DCM (shell)
        run: dcm analyze . --fatal-style --fatal-performance --fatal-warnings
        shell: bash

      - name: Test
        run: melos run test
